### ISSUE TITLE
Deploy the latest bundle locally  : mysql relationship problem with bundle.yaml file

### ISSUE THREAD

**Issue by moula** [charmed-hpc/slurm-bundles#38] opened 2023-09-09 13:24 UTC
Hello, 
I resume my tests with the latest versions especially the replacement of percona by mysql.
There is a problem with the relationship "mysql:mysql" and "slurmdbd:db" as written on the bundle.yaml file.
![Capture d’écran du 2023-09-09 15-21-21](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/249269e5-f1be-4d18-8152-0e96238ec411)

![Capture d’écran du 2023-09-09 15-22-10](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/8f6e1811-8da5-4582-8155-b23e8c7754a4)

Thank's. 
Moula.

**Comment by jaimesouza** [comment] 2023-09-12 12:22
Hello @moula!

Thank you for trying the bundles. 

They were relying on the legacy charms.

I am updating the bundles to use the current charms.

I will let you know as soon as they are updated.

**Comment by moula** [comment] 2023-09-12 12:29
Hello @jaimesouza Thank you very much. Good Job.

**Comment by jaimesouza** [comment] 2023-09-12 17:25
Hi @moula! Try again, please! Thanks!

**Comment by moula** [comment] 2023-09-13 09:55
Bonjour @jaimesouza . 
I just tried again, deploying it doesn't work. There is a problem with mysql and the creation of the instance on InnoDB...
![Capture d’écran du 2023-09-13 11-54-19](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/32909859-931d-449a-b394-9966f0a610bb)

**Comment by moula** [comment] 2023-09-13 10:04
If i try without " --overlay ./slurm-core/charms/latest-edge.yaml" 
![Capture d’écran du 2023-09-13 12-01-38](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/2094c508-07b3-41bb-9a4c-70c3c0443ff3)

**Comment by jaimesouza** [comment] 2023-09-13 11:49
Hello @moula! What's on MySQL logs?

`juju debug-log --include mysql/0 --replay`

**Comment by moula** [comment] 2023-09-13 13:01
@jaimesouza  
![Capture d’écran du 2023-09-13 14-53-56](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/b885fc6e-b6a1-48c3-9438-dfc597c4f646)

**Comment by moula** [comment] 2023-09-13 13:08
Ip mysql-server 127.0.0.1
Why not 172.200.0.126? 
Problème with MAAS in /etc/hosts ?

**Comment by jaimesouza** [comment] 2023-09-13 13:21
@moula, please log into the mysql node and double-check that:

`$ host mysql.tychecloud.org`

Apparently it is resolving to 127.0.0.1

It might be misconfigured on MAAS DNS.

It can also try to manually set the entry on /etc/hosts to test it.

**Comment by moula** [comment] 2023-09-13 14:24
@jaimesouza Modifying the /etc/hosts file manually does not solve the problem since when rebooting the mysql-server, it always returns to 127.0.0.1, it does not save 172.200.0.126. 
On Maas/Dns I can see that it is saved!!! 
![Capture d’écran du 2023-09-13 16-22-29](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/8bbbf69c-0c0b-4699-acc4-f74592d4d528)

I'll look closely at a problem on MAAS and I'll get back to you. 
Thank you. .

**Comment by moula** [comment] 2023-09-15 17:56
Bonjour @jaimesouza 
I looked at how to solve the mysql ip problem. The problem comes from the fact that Maas when deploying the bundle, so the installation of ubuntu only gives 127.0.0.1 as ip and does not take into account the fixed ips of mysql 192.168.70.126 or 172.200.0.126 for my configuration.
![Capture d’écran du 2023-09-15 19-48-50](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/b7425497-b8ce-4bbb-8f51-4ddd0f8a9564)

At this time, the host mysql.tychecloud.org command gives: mysql.tychecloud.org has address 127.0.0.1. 
While the MAAS server plays its role as a local DNS server: $ resolvectl status
![Capture d’écran du 2023-09-15 19-44-28](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/03b96b97-52f9-464b-8b2b-1c59fd65a93d)
![Capture d’écran du 2023-09-15 19-43-39](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/6a4ca3a1-fc43-4f9e-af1a-475e9bc269d6)
now the command: host mysql.tychecloud.org gives the 3 ips... 
![Capture d’écran du 2023-09-15 19-41-19](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/ce8691e4-8c77-4deb-9d55-9f1c8ee5a969)
Unfortunately, even if I retry the deployment of the bundle, the deployment script does not restart mysql on ip 192... but still 127.0.0.1 and it remains blocked!!!

![Capture d’écran du 2023-09-15 19-55-28](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/27d0e71d-62a4-4285-9783-d86529aa66f8)

Thank's 
Moula.

**Comment by moula** [comment] 2023-09-16 09:38
Bonjour @jaimesouza 
I tried another manual solution: modifying the listening IP address by changing the mysql bind from 127.0.0.1 to the host IP on the mysqld.cnf file, it didn't work!!! 
I have the impression that once mysql-charm is launched on 127.0.0.1 initially it does not try to restart on another IP despite the manual modifications and the fact of rebooting it!!!
Have a nice week end. 
Moula.

**Comment by jaimesouza** [comment] 2023-09-18 12:53
Hello @moula! Have you tried anything else after that? 

@derekcat do you have any idea on how to solve this?

**Comment by moula** [comment] 2023-09-18 13:37
Bonjour @jaimesouza 
I tried again this morning with the new versions of Maas and juju (It had lots of new features) but the problem is still the same.
1- Maas with its DNS module does not give the ip-fix address to the Ubuntu server during deployment (apart from 127.0.0.1).
2- Give the fixed IP to the deployed Ubuntu server and reboot it does not change anything. 
3- mysql charm  remains frozen on 127.0.0.1.
So automatic deployment of the bundle does not work.
Thank's
Moula.

**Comment by jaimesouza** [comment] 2023-09-18 14:04
Ok @moula! I am gonna include more people in this discussion. 

Would you like to join this team https://ubuntu.com/community/governance/teams/hpc?

We discuss lots of topics related to HPC and Ubuntu there. You can communicate with people on matrix and ask questions. There are knowledgeable guys who could help you with this issue or find someone else who could.

Let's move this discussion to there: https://matrix.to/#/#ubuntu-hpc:matrix.org

What do you think?

**Comment by taurus-forever** [comment] 2023-09-18 15:19
~@moula can you please re-try with MySQL from channel `8.0/candidate` (revision 193 at the moment)? Tnx!~
~The upcoming revision has several fixes which may help you, e.g. https://github.com/canonical/mysql-operator/pull/237~ 

Just noticed you are trying `8.0/edge` (revision 196)...

As replied [here](https://chat.charmhub.io/charmhub/pl/4ej8xdu3e7n13qp5mciufap4gy), the charm is getting IP from Juju in [this part of the code](https://github.com/canonical/mysql-operator/blob/f0abc404b8a2d12183708ba3007f650f46b019f5/src/charm.py#L545-L546).
Can you please check and share `juju show-unit mysql/0`? I suspect `private-address` is still localhost there.

**Comment by moula** [comment] 2023-09-18 15:40
Bonjour @taurus-forever 
![Capture d’écran du 2023-09-18 17-38-25](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/6499cf8d-468c-4cbf-9f75-8dc764673b50)

![Capture d’écran du 2023-09-18 17-39-12](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/f6e7cf41-9ad3-4833-ac89-c441aa61857f)

**Comment by moula** [comment] 2023-09-18 15:43
@taurus-forever 
This is the configuration of the mysql node
![Capture d’écran du 2023-09-18 17-41-01](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/ff2c743e-ef4f-4c94-a2a9-8034d5cde33b)

**Comment by derekcat** [comment] 2023-09-18 19:42
Hmmmm, does the node still get the wrong DNS entries if it's released from the model and redeployed elsewhere?
@jaimesouza would know better if the charm would pick up on changes, but I suspect it won't and you'd have to redeploy that part of the model (reapply bundle) after verifying that the node has the correct DNS entries deployed in a testing model.

**Comment by phvalguima** [comment] 2023-09-19 08:53
Hi @derekcat @jaimesouza @moula I was reviewing your comments.
If you check the link shared by @taurus-forever, I believe this is [the part of the code](https://github.com/canonical/mysql-operator/blob/f0abc404b8a2d12183708ba3007f650f46b019f5/src/charm.py#L546) affecting you.

One thing I noticed from your prints is that ```bind-address``` is not defined in your outputs of ```show-unit```.

Do you mind running this command:
```
# Juju 2.9.x
juju run --unit mysql/0 -- network-get database-peers
# Juju 3.1.x
juju exec --unit mysql/0 -- network-get database-peers
```

**Comment by moula** [comment] 2023-09-19 13:53
Bonjour @phvalguima 
I use juju 2.9 
![Capture d’écran du 2023-09-19 15-51-38](https://github.com/omnivector-solutions/slurm-bundles/assets/1804815/6fca7493-083c-4701-b961-31a4f5e72263)

Thank you. 
Moula.

**Comment by moula** [comment] 2023-09-19 14:24
Bonjour @jaimesouza As you know it's a bug with mysql and ip...
I'm waiting for this to be fixed and tested by the Canonical QA team. 
II would like to thank you for your reaction and answers and the whole team.
I'm going to leave you calm for a little while to get back to the Kubeflow+Mlflow+cos projects..
Merci beaucoup. 
Moula.

**Comment by jaimesouza** [comment] 2023-09-19 16:04
Hi @moula! No problem!
Glad to help! 
If you need any assistance, just let us know.

**Comment by jaimesouza** [comment] 2023-10-20 12:12
Hey @moula!

Have the issues been resolved? If so, how did you do it?

I am having the same issue on MySQL charm on vSphere.

**Comment by moula** [comment] 2023-10-20 17:48
Bonsoir @jaimesouza 
Sorry but the issue is still there. 
![Capture d’écran du 2023-10-20 19-47-17](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/a201d0ce-3967-467a-91ae-b17d98e72204)
![Capture d’écran du 2023-10-20 19-46-33](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/c3f85b4c-88b0-4c1d-82d5-efc026fb057f)
![Capture d’écran du 2023-10-20 19-43-08](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/487f5337-9b36-4ef2-83cf-87f19ab3d5aa)

**Comment by jaimesouza** [comment] 2023-10-24 16:36
Hey @moula!

@NucciTheBoss from Canonical is also investigating this issue.

I will let you know when we have a solution for it.

Thank you!

**Comment by NucciTheBoss** [comment] 2023-10-24 22:34
Hi there @moula - are you sure that you have DHCP configured correctly in your MAAS cluster? Reason saying is that I am looking through the screenshots that you have shared and it seems that your nodes are having trouble connecting to the network. For example, I notice in your attached screenshots that your nodes are failing to pull the SLURM packages from Omnivector's PPA on Launchpad. It's likely that they are unable to connect to the external network. What's likely happening with MySQL is that it is defaulting to `/etc/hosts` because it is either unable to contact your DNS server, or the node has not been assigned an IP by your DHCP server.

Could you both (including @jaimesouza) make sure that you have your DHCP and DNS servers configured correctly and that your deployed nodes can reach the external network. e.g. does `ping ubuntu.com` successfully transmit and receive ICMP packets? I'm not able to reproduce these issues you're having on either LXD, OpenStack, AWS, or GCP, and they usually include their own DNS and DHCP services.

**Comment by NucciTheBoss** [comment] 2023-10-24 22:36
See section 10.4 of the [Debian networking reference](https://qref.sourceforge.net/quick/ch-gateway.en.html) for an explanation on why MySQL is resolving to 127.0.1.1 if you do not have an assigned IP address for your instance.

**Comment by wolsen** [comment] 2023-10-24 23:34
> Hi there @moula - are you sure that you have DHCP configured correctly in your MAAS cluster? Reason saying is that I am looking through the screenshots that you have shared and it seems that your nodes are having trouble connecting to the network. For example, I notice in your attached screenshots that your nodes are failing to pull the SLURM packages from Omnivector's PPA on Launchpad. It's likely that they are unable to connect to the external network. What's likely happening with MySQL is that it is defaulting to `/etc/hosts` because it is either unable to contact your DNS server, or the node has not been assigned an IP by your DHCP server.

Looking at the error reported from the slurmd/0 unit (shown in the first 2 screen captures provided in [this comment](https://github.com/charmed-hpc/slurm-bundles/issues/38#issuecomment-1773150675), I am curious if there's a network proxy in the way. Can you comment on whether this is the case or not? If so, have you set any model configuration options in Juju for the proxies? Additionally, I will note that the add-apt-repository command for resolving the PPA URL in the short format will make queries out to the launchpad APIs. If these are restricted by local network settings, it will cause these queries to fail and be unable to resolve the target URLs for adding the apt-source strings. This is something that can, and should be, handled by the slurm charms here.

Additionally, the error reported by the mysql-router/0 unit is indicating that the charmed-mysql snap is already installed. The installation hook is fairly simple, where the primary purpose is to install the snap itself. However, perusing the code here, I can see a scenario when the asynchronous task of installing the snap fails to complete before the charm logic times out the installation ultimately causing the hook to error out. Upon re-running the installation hook, there's a [simple check](https://github.com/canonical/mysql-router-operator/blob/e8327152b0b6c3733e6585b6117766d4d9c08831/src/snap.py#L28) that the mysql-router charm is using to see if the snap is already installed. However, it doesn't take into account that the snap may already be installed and re-executing on a failed install hook scenario. This may or may not be by design, but I'll raise a bug over against the mysql-router charm to be able to handle this scenario and let them weigh in on it (cc @taurus-forever).

These stack traces provided don't capture the mysql-operator logs themselves. However, the juju status output provided in the 3rd screenshot clearly indicates that the mysql service was unable to be configured which matches the original condition. Ultimately, I think there's a few things that need to be cleared up here - but the data there doesn't help identify what the problem is in the mysql-operator case.

**Comment by moula** [comment] 2023-10-24 23:45
@NucciTheBoss Hi Jason. Thank you for your message and your work. I just want to tell you that on this platform, I have 15 bundles that have always worked. Sunbeam bundle, openstack bundle, microk8s bundle, microceph, Charmed-k8s, kubeflow, mlflow, cos, postgresql, mysql... Even the old hpc bundle on focal worked, so you understand what I mean. This is the only bundle that no longer deploys since you replaced percona with mysql-8. one bundle out of 15 which is no longer deployed on my platform with 25 Asus physical servers!!!. Even the mysql bundle doesn't deploy on its own, I sent the bug to the mysql bundle team some time ago but I managed to deploy it by individual charm, to tell you the truth. Something else I tested since yesterday on juju-controller 2.9 and on juju-controller 3.1 but the problem is the same. even now I'm still testing.
![Capture d’écran du 2023-10-25 01-26-53](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/d9c7d761-c5fd-4fed-97c3-616842021730)
![Capture d’écran du 2023-10-25 01-24-55](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/feb3eb1d-f861-4b56-8743-538581148f21)
![Capture d’écran du 2023-10-25 01-24-37](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/430088d3-87e5-48ea-9f94-28b73e8312ee)
![Capture d’écran du 2023-10-25 01-24-10](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/9f4e4620-e915-4502-9890-06ddf1077271)
![Capture d’écran du 2023-10-25 01-23-42](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/487eb0be-0d62-4758-87d2-cc67b35b95b4)

**Comment by moula** [comment] 2023-10-24 23:48
@NucciTheBoss The IP of the mysql node is fixed at the maas level. 192.168.70.130 && 172.200.0.130. 
![Capture d’écran du 2023-10-25 01-47-10](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/e441395d-3608-4613-9ba3-d5961f5e7a96)

**Comment by moula** [comment] 2023-10-24 23:52
I restarted the live deployment but the issue is still the same : 
![Capture d’écran du 2023-10-25 01-51-37](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/317cbfb2-9ab1-4564-ae2e-9f42c9d83bff)
![Capture d’écran du 2023-10-25 01-51-10](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/d7e5439e-a314-4a2d-9111-6c2680e45a65)

**Comment by moula** [comment] 2023-10-24 23:54
![Capture d’écran du 2023-10-25 01-53-51](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/b3f133de-0a69-4bf9-bb6b-12b5c7e3ad16)

**Comment by moula** [comment] 2023-10-24 23:58
> > Hi there @moula - are you sure that you have DHCP configured correctly in your MAAS cluster? Reason saying is that I am looking through the screenshots that you have shared and it seems that your nodes are having trouble connecting to the network. For example, I notice in your attached screenshots that your nodes are failing to pull the SLURM packages from Omnivector's PPA on Launchpad. It's likely that they are unable to connect to the external network. What's likely happening with MySQL is that it is defaulting to `/etc/hosts` because it is either unable to contact your DNS server, or the node has not been assigned an IP by your DHCP server.
> 
> Looking at the error reported from the slurmd/0 unit (shown in the first 2 screen captures provided in [this comment](https://github.com/charmed-hpc/slurm-bundles/issues/38#issuecomment-1773150675), I am curious if there's a network proxy in the way. Can you comment on whether this is the case or not? If so, have you set any model configuration options in Juju for the proxies? Additionally, I will note that the add-apt-repository command for resolving the PPA URL in the short format will make queries out to the launchpad APIs. If these are restricted by local network settings, it will cause these queries to fail and be unable to resolve the target URLs for adding the apt-source strings. This is something that can, and should be, handled by the slurm charms here.
> 
> Additionally, the error reported by the mysql-router/0 unit is indicating that the charmed-mysql snap is already installed. The installation hook is fairly simple, where the primary purpose is to install the snap itself. However, perusing the code here, I can see a scenario when the asynchronous task of installing the snap fails to complete before the charm logic times out the installation ultimately causing the hook to error out. Upon re-running the installation hook, there's a [simple check](https://github.com/canonical/mysql-router-operator/blob/e8327152b0b6c3733e6585b6117766d4d9c08831/src/snap.py#L28) that the mysql-router charm is using to see if the snap is already installed. However, it doesn't take into account that the snap may already be installed and re-executing on a failed install hook scenario. This may or may not be by design, but I'll raise a bug over against the mysql-router charm to be able to handle this scenario and let them weigh in on it (cc @taurus-forever).
> 
> These stack traces provided don't capture the mysql-operator logs themselves. However, the juju status output provided in the 3rd screenshot clearly indicates that the mysql service was unable to be configured which matches the original condition. Ultimately, I think there's a few things that need to be cleared up here - but the data there doesn't help identify what the problem is in the mysql-operator case.

Hi @wolsen No, it was just an oversight in this image. Since then I have tried again several times as currently live.

**Comment by NucciTheBoss** [comment] 2023-10-25 00:17
@moula thank you for refreshing your deployment; clears up some of my initial confusion. Can you ssh into each of the nodes to ensure that they can access the external network?

For example, could you try contacting ubuntu.com from mysql/0:

```
juju ssh mysql/0
ping ubuntu.com
```

Can you then verify that mysql/0 can reach slurmdbd/0?

```
ping <ip_for_slurmdbd/0>
```

I just want to ensure that your nodes can reach the network. This will help narrow down where the issue is located within the cluster.

**Comment by moula** [comment] 2023-10-25 00:23
@NucciTheBoss 
![Capture d’écran du 2023-10-25 02-22-45](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/75197921-649f-4590-9345-7ab786004d9a)

**Comment by moula** [comment] 2023-10-25 00:29
@NucciTheBoss I have another error message, after rebooting the nodes as requested during the installation of the jammy OS.

![Capture d’écran du 2023-10-25 02-26-25](https://github.com/charmed-hpc/slurm-bundles/assets/1804815/8b52eb78-371d-48cf-b30d-4661cf9a95c4)

**Comment by moula** [comment] 2023-10-25 00:35
@NucciTheBoss I have a question : 
After modifying the ips of the nodes in the file: /etc/cloud/templates/hosts.debian.tmpl and restarting the nodes. Are there any commands to force the bundle deployment to re-execute?
moula@maas:~/slurm-bundles$ juju deploy ./slurm-core/bundle.yaml  --overlay ./slurm-core/charms/latest-edge.yaml --force
No changes to apply.

**Comment by jaimesouza** [comment] 2023-10-25 13:17
@moula 

The issue is on /`etc/hosts` indeed. For some reason, my vSphere VM comes with the following line:

`127.0.1.1 juju-39c062-25 juju-39c062-25`

You have the same thing.

I have tested pre-adding the machine, commenting that line, rebooting the machine, and deploying the charm on it after that.

It deployed successfully!

I need to make the changes on `/etc/cloud/templates/hosts.debian.tmpl ` to make it persistent after reboot.

**Comment by NucciTheBoss** [comment] 2023-10-25 13:59
Thanks @jaimesouza for testing this out. This can be a stop-gap patch in the short term; however, we should identify what the root cause of the issue is.

We're looking at what the issue could possibly be within the MySQL operator. It's obvious now that the nodes in both your clouds are being assigned IPs via DHCP and able to contact the network, so we need to figure out why the MySQL operator is resolving the IP to be 127.0.1.1. Don't want to patch /etc/hosts if we don't have to 😅

**Comment by NucciTheBoss** [comment] 2023-10-25 14:06
> @NucciTheBoss I have a question : 
> After modifying the ips of the nodes in the file: /etc/cloud/templates/hosts.debian.tmpl and restarting the nodes. Are there any commands to force the bundle deployment to re-execute?
> moula@maas:~/slurm-bundles$ juju deploy ./slurm-core/bundle.yaml  --overlay ./slurm-core/charms/latest-edge.yaml --force
> No changes to apply.

I don't think so. Generally you shouldn't need to reexecute the bundle deployment as that goes against the autonomous nature of Juju. Juju will automatically attempt to rerun failed hooks.

If you have failed hooks in your cluster, you can follow this documentation here for how to retrigger the hook: https://juju.is/docs/sdk/debug-a-charm#heading--debug-a-single-failing-hook. This documentation is more meant for debugging, but you can use it to rerun hooks should you need too!

**Comment by moula** [comment] 2023-10-25 14:38
> @moula
> 
> The issue is on /`etc/hosts` indeed. For some reason, my vSphere VM comes with the following line:
> e
> `127.0.1.1 juju-39c062-25 juju-39c062-25`
> 
> You have the same thing.
> 
> I have tested pre-adding the machine, commenting that line, rebooting the machine, and deploying the charm on it after that.
> 
> It deployed successfully!
> 
> I need to make the changes on `/etc/cloud/templates/hosts.debian.tmpl ` to make it persistent after reboot.

@jaimesouza Thank's. 
I did the same thing with the mysql node and added the ip fix to it once the ubuntu OS was installed and rebooted but for the moment it doesn't work, hence my last question to @NucciTheBoss. I hope that with your modifications it will work. Even they are making changes to the mysql-router charm. 
Thank you to all of you.

**Comment by moula** [comment] 2023-11-13 11:11
hi guys. I think our bug will be fixed soon. I will test it as soon as it is applied. THANKS. 
https://github.com/canonical/mysql-router-operator/issues/84. 
Moula.

**Closed** 2024-01-17 21:04 UTC
